CREATE TABLE PRODUCTOS (
    ProductoId INTEGER PRIMARY KEY IDENTITY(1,1)
    Nombre VARCHAR(100) NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL,
    Categoria VARCHAR(50) NOT NULL,
);

CREATE TABLE COMPRETENCIA_PRECIOS (
    CompetenciaId INTEGER PRIMARY KEY IDENTITY(1,1)
    NombreProducto VARCHAR(100) NOT NULL,
    PrecioCompetencia DECIMAL (10,2) NOT NULL,
    Categoria VARCHAR(50) NOT NULL,
);